### ISSUE TITLE
After some ambiguous point in the game, Arthas can no longer lose hit points

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#954] opened 2023-01-07 15:36 UTC

**Comment by YakaryBovine** [comment] 2023-01-07 15:46
@SebastianTanoni Not caused solely by Icecrown event; already tried it. Renaming.

**Comment by YakaryBovine** [comment] 2023-01-07 15:47
Duplicate of #953

**Closed by YakaryBovine** 2023-01-07 15:47 UTC
