### ISSUE TITLE
Camera doesnt zoom out after intro

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#182] opened 2022-11-11 14:21 UTC

**Comment by SebastianTanoni** [comment] 2022-11-11 14:21
-far command also does not work

**Comment by SebastianTanoni** [comment] 2022-11-11 14:22
-cam 2000 command also does not work

**Comment by YakaryBovine** [comment] 2022-11-11 21:37
Closing as duplicate of #266.

**Closed by YakaryBovine** 2022-11-11 21:37 UTC
Labels: bug, legacies
