### ISSUE TITLE
No channel bar when velen channels at tempest keep

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#252] opened 2022-11-11 18:53 UTC
![image](https://user-images.githubusercontent.com/47048283/201410821-799fa56f-d827-49ff-b995-5420d777b060.png)

**Comment by YakaryBovine** [comment] 2022-11-11 20:39
Closing as duplicate of #162.

**Closed by YakaryBovine** 2022-11-11 20:39 UTC
Labels: bug, legacies
