### ISSUE TITLE
Portal from Tempest Keep to Argus - no visual portal 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2674] opened 2023-11-17 19:11 UTC
When Velen channels at Tempest Keep for 3 minutes in order to open a portal between Tempest Keep and Argus, the following issues occur:

- No timer in top right corner (unsure if intended) 
- Although a useable portal between two points is created and you are able to use them successfully - there is no apparent Portal model

**Comment by YakaryBovine** [comment] 2024-01-12 10:11
I imagine the timer not showing is intentional because this isn't a global quest that players need to be aware of.
The portal is showing for me - that white thing is the portal. Can re-open this if we get some reproduction steps.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/d06d3205-37f7-435e-be96-0c296ad965d0)

**Comment by Technopig1992** [comment] 2024-01-12 13:25
I did check with Sebas  who said there should be a slipstream style purple one there but I can confirm the white circle is there each time . Timer makes sense

**Comment by YakaryBovine** [comment] 2024-01-13 06:29
@Technopig1992 Oh ok, thanks. @SebastianTanoni can you confirm here that there used to be a purple portal, and if so, do you know when it broke?

**Comment by YakaryBovine** [comment] 2024-03-22 09:50
Judging by lack of reply here this is not important so closing.

**Closed by YakaryBovine** 2024-03-22 09:50 UTC
Labels: bug, awaitingResponse
