### ISSUE TITLE
maybe rewrite starting tips?

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#741] opened 2022-12-23 10:38 UTC
![image](https://user-images.githubusercontent.com/119281194/209321560-d92f9d6b-461c-4d7b-b509-593cd0286be8.png)

**Comment by TracyTheBoy** [comment] 2022-12-25 11:56
related to #754

**Comment by YakaryBovine** [comment] 2022-12-26 09:08
Closed as duplicate of #754

**Closed** 2022-12-26 09:07 UTC
