### ISSUE TITLE
Goblin Offshore Investment Quest 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2892] opened 2024-04-14 14:49 UTC
Reward states you can now train Traders which is untrue as they are locked behind Business Expansion -

Which subsequently locks both types of Traders (Zeppelin and Ship) behind the same objective. 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/d887e698-782d-4cdd-a5e1-1372cef6fc8b)

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/10b02716-b4fe-4b4a-827e-9ee8f04bf24f)

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/a8ceeeaa-4e9e-46b7-8274-55b41991cd57)

**Comment by YakaryBovine** [comment] 2024-04-14 22:17
@Technopig1992 Thanks, I've added this to our Old Gods board since I think it'll have to be part of updating Goblins to the new system. Unfortunately likely to be a bit too complicated to fix in `main`.

**Comment by YakaryBovine** [comment] 2024-04-20 10:13
Fixed in https://github.com/AzerothWarsLR/WarcraftLegacies/commit/3f3f6383cb75f8e478a0e1f21dffa11a94e837f5
I merely updated the quest tooltips to reflect reality, presuming that the mechanic is working as intended.

**Closed by YakaryBovine** 2024-04-20 10:13 UTC
Labels: bug, investigation
