### ISSUE TITLE
Thrall and kael randomly got lvl 20

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#554] opened 2022-11-29 00:34 UTC

**Comment by YakaryBovine** [comment] 2022-11-29 03:37
@SebastianTanoni Do you have any more info on this? Maybe even just roughly what turn it was?

**Comment by TracyTheBoy** [comment] 2022-11-29 06:35
@YakaryBovine Pretty sure what happened was this.
Draenai left outland around turn 10, that caused Kul, Quel and troll second chances to trigger for some reason and that caused all the allies in their teams to get lvl 20 heroes. #555 is basically the same problem

**Comment by YakaryBovine** [comment] 2022-11-29 09:28
Excellent, thankyou. Closing as duplicate of #555.

**Closed by YakaryBovine** 2022-11-29 09:28 UTC
Labels: bug, legacies, C#
