### ISSUE TITLE
Frostwolf Quest are split between Map info and Quests?

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#185] opened 2022-11-11 14:27 UTC
![image](https://user-images.githubusercontent.com/47048283/201360394-953a1ee8-f1cf-4db8-9e8c-7a9ec26fbf51.png)

**Comment by YakaryBovine** [comment] 2022-11-11 21:32
Closing as intended.

**Closed by YakaryBovine** 2022-11-11 21:32 UTC
Labels: bug, legacies
