### ISSUE TITLE
Full Scale escalation research bug

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#878] opened 2023-01-04 19:37 UTC
![image](https://user-images.githubusercontent.com/47048283/210635466-b65842f9-4481-47d2-aecf-f46d57e28599.png)

**Comment by YakaryBovine** [comment] 2023-01-04 20:49
Duplicate of https://github.com/AzerothWarsLR/WarcraftLegacies/issues/854

**Closed by YakaryBovine** 2023-01-04 20:49 UTC
