### ISSUE TITLE
Golbin Zeppelin Traders 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2890] opened 2024-04-14 14:35 UTC
Income works correctly but all traders gather in one spot and do not move 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/354fb3cc-643e-4421-996a-688d18bfa1cd)

**Comment by YakaryBovine** [comment] 2024-04-20 10:12
@Technopig1992 I don't suppose you know how to replicate this, or can ask the person who reported it how they did it?
If I do the following:
1. Start the game as Bilgewater
2. Complete Offshore Investments by cheating
3. Use the synergy cheat
4. Use the warpten cheat
5. Train many Zeppelins

I get my Zeppelins flying around as intended: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/0c7e2f89-ac12-43fc-8cb5-81396094e048)

**Comment by Technopig1992** [comment] 2024-04-20 11:13
Strange . It was me who made the initial report as I noticed it while checking some query clarity issues . I was in single player and destroyed the appropriate buildings using a -hp 0 and took ownership of the required CPs using -owner , then trained the Zeppelins and noticed them gather. 

I'll try and replicate again and close down as not planned if I can't seem to.

**Comment by YakaryBovine** [comment] 2024-05-05 10:53
From the conversation above it sounds like we can close this one. But the screenshot does prove it happens in *some* circumstance so if it does come up again let me know.

**Closed by YakaryBovine** 2024-05-05 10:53 UTC
Labels: bug, C#
