### ISSUE TITLE
Scarlet Bishop's Sanctify permanently silences him when he uses it near himself

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2842] opened 2024-04-05 16:34 UTC
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/b8527c13-e957-45c6-9eb5-da1c5d83d550)

**Comment by YakaryBovine** [comment] 2024-04-05 23:47
Yeah just tried this out, really easy to reproduce.
I imagine the best fix will be to make it not target Self.

**Comment by YakaryBovine** [comment] 2024-04-13 22:38
Not fixed, just tried it in `dev`: 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/4e786743-66b1-4c5a-be7a-af5e0518a2a2)

**Comment by YakaryBovine** [comment] 2024-04-28 20:24
@SebastianTanoni Another good one to do I think. This will possibly have to be done as part of a major version since it may involve replacing the spell (or doing some custom code).

If you can exhaust the possibility of fixing it in the object editor you can re-assign it to me and I'll do some code. I'm thinking if a dummy unit casts the actual spell the bug will go away.

**Comment by SebastianTanoni** [comment] 2024-04-28 22:12
My idea was to give them normal silence and call it a day

**Comment by SebastianTanoni** [comment] 2024-04-28 22:13
Everything I tried didn't work, so except if you want to code, I'd just go with normal silence

**Comment by YakaryBovine** [comment] 2024-04-28 23:18
> Everything I tried didn't work, so except if you want to code, I'd just go with normal silence

Let's do normal silence!

**Closed** 2024-05-01 10:36 UTC
Labels: bug, worldEditor
