### ISSUE TITLE
Invisible platforms are also removed

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#248] opened 2022-11-11 18:47 UTC
![image](https://user-images.githubusercontent.com/47048283/201409980-cd8f5903-3bed-4cb1-baeb-d697d18498eb.png)

**Comment by YakaryBovine** [comment] 2022-11-13 04:40
Closing as duplicate of #238.

**Closed by YakaryBovine** 2022-11-13 04:40 UTC
Labels: bug, legacies
