### ISSUE TITLE
Lordaeron Quests also divided

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#195] opened 2022-11-11 14:48 UTC
![image](https://user-images.githubusercontent.com/47048283/201364242-7799b2dc-0eba-4ccd-9e18-c526c9bce5aa.png)

**Comment by YakaryBovine** [comment] 2022-11-11 21:24
Closing as intended.

**Closed by YakaryBovine** 2022-11-11 21:24 UTC
Labels: bug
