### ISSUE TITLE
Zangermarsh Quest

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3092] opened 2024-06-24 02:49 UTC
If the player fails the quest (time limit) they are unable to train the air units there

**Comment by YakaryBovine** [comment] 2024-06-24 04:15
@Technopig1992 This one's not a bug - the original reason that quests grant bases on failure was so that **enemies** could still destroy the base, not so that players would freely unlock things they need. This is true for most if not all quests of this nature - they give you the base, but don't give any associated rewards. I'll close this, but we can take it to #brainstorming or #design-forum on Discord if it seems like something we need to change.

**Closed by YakaryBovine** 2024-06-24 04:15 UTC
Labels: bug, C#
