### ISSUE TITLE
Oil Supply doesnt drain oil when transfering to transports

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#234] opened 2022-11-11 17:47 UTC

**Comment by YakaryBovine** [comment] 2022-11-11 20:50
@SebastianTanoni Let's have a talk again about the goblin oil mechanics. I think it'd be great if we made more use of the Power system and devised something really easy to use.

**Comment by YakaryBovine** [comment] 2022-11-15 08:11
Closing as this is not a bug anymore. Oil is automatically transferred between units now.

**Closed by YakaryBovine** 2022-11-15 08:11 UTC
Labels: bug, legacies
