### ISSUE TITLE
Grommash Hellscream's spells are permanently disabled if he uses his abilities in a specific sequence

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2295] opened 2023-09-30 23:43 UTC

**Comment by SebastianTanoni** [comment] 2023-09-30 23:57
Keep in mind its just a theory, im not 100% sure this is the method to reproduce

**Comment by Ripzss** [comment] 2023-10-13 22:02
To reproduce Windwalk -> Avatar in windwalk -> Whirldwind on alot of enemites seems to have been a reliable way for me to reproduce this

**Comment by Ripzss** [comment] 2023-10-13 22:03
Changing Ultimate easiset way to Fix this, 
Suggestions from me:
Change to Galen ult (instant full hp heal)

**Comment by YakaryBovine** [comment] 2023-10-23 21:14
Unassigning Ripzss just in case anyone is able to pick this up. He's provided reproduction steps. We probably do indeed need to just replace at least one of the abilities involved as the bug seems to be a vanilla one.

**Comment by YakaryBovine** [comment] 2023-11-14 22:35
Madsen's investigation seems to suggest that this can't be fixed without replacing one of the abilities involved. That makes this a Feature ticket.

**Closed** 2023-11-18 02:45 UTC
Labels: bug, worldEditor, feature
