### ISSUE TITLE
zinrokh sus

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#626] opened 2022-12-05 21:39 UTC
https://www.youtube.com/watch?v=pEipb2MH0Eg
abuse? bug? feature?

**Comment by YakaryBovine** [comment] 2022-12-07 02:00
Thankyou. Closed as duplicate of https://github.com/AzerothWarsLR/WarcraftLegacies/issues/628.

**Closed by YakaryBovine** 2022-12-07 02:00 UTC
