### ISSUE TITLE
Gilneas quests are all missing

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#261] opened 2022-11-11 19:22 UTC
![image](https://user-images.githubusercontent.com/47048283/201414980-bf454e1b-30cf-42a4-9290-69cf5faeee03.png)

**Comment by YakaryBovine** [comment] 2022-11-11 20:30
Closing as this is a duplicate of #84.

**Closed by YakaryBovine** 2022-11-11 20:30 UTC
Labels: bug, legacies
